# Generated by Django 2.1.2 on 2019-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Creation_Date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
