# Generated by Django 2.1.2 on 2019-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielib', '0002_auto_20190611_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
