# Generated by Django 2.1.2 on 2019-06-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielib', '0003_auto_20190611_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Video',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
