# Generated by Django 2.1.2 on 2019-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielib', '0004_auto_20190611_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Type',
            field=models.CharField(choices=[('Film', 'FILM'), ('Game', 'GAME')], max_length=100),
        ),
    ]
