# Generated by Django 2.1.2 on 2019-06-11 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movielib', '0005_auto_20190611_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Modified_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 19, 39, 47, 795729, tzinfo=utc), verbose_name='date modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='Type',
            field=models.CharField(choices=[('Film', 'Film'), ('Game', 'Game')], max_length=100),
        ),
    ]
