# Generated by Django 2.1.2 on 2019-06-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielib', '0007_auto_20190611_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(null=True, upload_to='', verbose_name='')),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('Film', 'Film'), ('Game', 'Game')], max_length=100)),
                ('Client', models.CharField(max_length=200)),
                ('Project_Manager', models.CharField(max_length=200)),
                ('Creation_Date', models.DateTimeField(auto_now_add=True)),
                ('ModifiedD', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='movie',
        ),
    ]
